
[[numbering]]
== Project/document identifier

=== General

ELF implements a numbering system for projects/documents.

=== Project index

A project/document index shall be maintained on the ELF
website with documents listed by number, name, and type.

[[project-code]]
=== Project code

. The project code shall be of the form `[n]`, where `[n]` is any
selected positive integer of five (5) or less digits.

. The numbering system applies across all project types.
Different project types shall not share an identical project code.

. The project code shall be assigned on proposal acceptance
of the project.

. Co-published documents shall attempt to use an identical project
code in both ELF and at the collaborative publisher to prevent
potential ambiguity, if possible.


=== Document identifier

==== Representation

The document identifier takes the form of `[type][stage] [code][:][y]`, where:

* `[type]` is the document identifier prefix;
* `[stage]` is the document stage;
* `[code]` is the project code of the project that created the document; and
* `[y]` is the 4-digit edition year.


==== Edition year

The edition year is the calendar year in which the document is published.
On updates, a document will retain the same project code but may be
assigned a different edition year in which the update is published.


==== Co-publishing

Co-published documents shall incorporate codes from all collaborative
publishing parties in the document identifier, joined together via a
"`solidus`" sign ("```/```").

[example]
ELF deliverables co-published with ISO are referenced as "`ELF/ISO`",
with IETF as "`ELF/IETF`".


[[document-type]]
==== Document types

Document types shall be represented in the "`type`" as follows:

. Standard, "`ELF`"

. Directive, "`ELF/DIR`"

. Guide, "`ELF/Guide`"

. Specification, "`ELF/S`"

. Report, "`ELF/R`"

. Amendment, "`ELF/Amd`"

. Technical corrigendum, "`ELF/Cor`"

. Administrative, "`ELF/A`"

[example]
"`ELF/Guide/DS 38002:2018`" is an ELF Guide at DS stage with
project number 38002, published in 2018.


[[document-stage]]
==== Document stages

Document stages shall be represented in the "`stage`" as follows:

. Published, "``` ```" (blank)

. Final draft standard, "```/FDS```"

. Draft standard, "```/DS```"

. Technical committee draft, "```/CD```"

. Project group draft / Working draft, "```/WD```"


[example]
"`ELF/FDS 10668:2018`" is an ELF standard document at FDS stage
with project number 10668, published in 2018.

[example]
"`ELF/Guide/DS 20080:2018`" is an ELF guide at DS stage with
project number 20080, published in 2018.


NOTE: Existing documents can be retrofitted to the scheme as practical.

