[[authority]]
== Authority

=== General

The TCB is responsible for developing the corresponding processes
and tools, and for their employment.

[[authority-tcb]]
=== Technical Coordination Board

The TCB is responsible for:

* policy development: providing recommendations to the Board of
  Directors on the ELF standardization and publication processes;

* policy establishment: developing and supporting process
  documents, including:

** this document; and
** ELF publication requirements; and

* maintenance: periodic review and perform amendments necessary
  to support the processes and requirements established in this
  document;

* execution: faithful execution and maintenance of the ELF
  standardization process;

* enforcement: enforcing ELF publication requirements on the publication
  of ELF deliverables;

* mediation: raising issues and problems encountered concerning the processes
  and procedures described in this document to the Board of Directors for
  further consideration; and

* coordination: supporting liaisons between ELF technical committees and
  project teams with corresponding parties of external standardization
  bodies.
